Added microservice for tenders
PSW-2020-ORG1/MedbayTech pull request #116
Opened 2021-01-26 20:23 UTC by L4v

2021-01-27 06:13 UTC, jelena-vlajkov requested changes
Change hardcoded paths in RssController.

2021-01-27 06:55 UTC, L4v commented
> 
> 
> Change hardcoded paths in RssController.

Fixed.

2021-01-27 22:56 UTC, jelena-vlajkov approved these changes

2021-01-28 00:02 UTC, OakenKnight approved these changes

2021-01-28 00:03 UTC, merged