Frontend logic for making an appointment by recommendation strategy
PSW-2020-ORG1/MedbayTech pull request #50
Opened 2020-12-04 21:57 UTC by VujicGit

2020-12-04 22:05 UTC, jelena-vlajkov requested changes
Change the 2 little things from my review and merge new changes from develop.

2020-12-04 22:05 UTC, jelena-vlajkov commented on Backend/Users/Service/DoctorService.cs
> +
Try to name variables differently, e.g. allDoctors and filteredDoctors.

2020-12-04 22:05 UTC, jelena-vlajkov commented on Backend/Users/Service/Interfaces/IDoctorService.cs
> +
You can remove Specialization from GetDoctorBySpecialization, the parameter is self explanatory.

2020-12-06 13:16 UTC, jelena-vlajkov requested changes

2020-12-06 13:16 UTC, jelena-vlajkov commented on Backend/Schedules/Model/Appointment.cs
> +
If it is not canceled by patient, then it is probably finished. Two bool values for very similar things.

2020-12-06 13:16 UTC, jelena-vlajkov commented on Backend/Schedules/Service/AppointmentService.cs
>          }
You can remove from method name _ByDoctorAndDate_, the parameters are self explanatory. If you name it GetAvailableBy(string doctorId, DateTime date) it will be evident you are trying to filter appointments by id and date.

2020-12-06 13:16 UTC, jelena-vlajkov commented on Backend/Schedules/Service/AppointmentService.cs
> -
Useless method, you can put that in if statement it will not change clean code principles a lot.

2020-12-06 13:16 UTC, jelena-vlajkov commented on Backend/Schedules/Service/AppointmentService.cs
Also, you can remove _DoctorAndDate_, and name the method GetBy or if you want to be more precise, GetScheduledBy.

2020-12-06 13:16 UTC, jelena-vlajkov commented on Backend/Schedules/Service/AppointmentService.cs
I think it's better to raise an exception in doctorWorkDayRepo then to compare the return value with null if you don't find any work days. Then the lines 71-72 are not needed.

2020-12-06 13:16 UTC, jelena-vlajkov commented on Backend/Schedules/Service/AppointmentService.cs
> +            for (int i = 0; i < endTime - 1; i++)
Magic number. You should make appointment duration configurable.

2020-12-06 13:16 UTC, jelena-vlajkov commented on Backend/Users/Service/Interfaces/IDoctorService.cs
> +
GetDoctorsBy *** not GetDoctors

2020-12-06 13:54 UTC, VujicGit commented on Backend/Schedules/Model/Appointment.cs
> +
We must count how many times the **patient** has canceled appointment during the month

2020-12-07 18:31 UTC, jelena-vlajkov approved these changes
Thank you for editing requested changes!

2020-12-07 18:36 UTC, st3fan7 approved these changes

2020-12-07 18:39 UTC, merged