Feature web observe appointment
PSW-2020-ORG1/MedbayTech pull request #55
Opened 2020-12-11 12:49 UTC by Markovic-Filip

2020-12-12 18:19 UTC, st3fan7 approved these changes, later dismissed

2020-12-12 18:23 UTC, st3fan7 requested changes
Please resolve the conflicts.

2020-12-12 19:32 UTC, jelena-vlajkov requested changes
Resolve conflicts before you make a PR + change the things I marked.

2020-12-12 19:32 UTC, jelena-vlajkov commented on WebApplication/Controller/AppointmentController.cs
> +        [HttpGet("allSurveyableAppointments")] //GET api/Appointment
Delete commented lines.

2020-12-12 19:32 UTC, jelena-vlajkov commented on Backend/Schedules/Repository/IAppointmentRepository.cs
>      }
Please follow the convention. 
getAppointmentById -> GetAppointmentById, etc.

2020-12-12 19:32 UTC, jelena-vlajkov commented on Backend/Schedules/Repository/IAppointmentRepository.cs
> +        IEnumerable<Appointment> GetAppointmentsByPatientId(string Id);
On the other hand, every sql repository will inherit MySqlRepository class and in that class you can find methods like Update and GetObject, exact same methods you wanted to implement here.

2020-12-12 19:32 UTC, jelena-vlajkov commented on Backend/Schedules/Repository/MySqlRepository/AppointmentSqlRepository.cs
>          public Dictionary<int, Appointment> GetAppointmentsBy(DateTime date)
Useless method, base class already has GetObject.

2020-12-12 19:32 UTC, jelena-vlajkov commented on Backend/Schedules/Repository/MySqlRepository/AppointmentSqlRepository.cs
> +        }
You just returned base class Update, so you already have a function you need.

2020-12-12 19:32 UTC, jelena-vlajkov commented on Backend/Schedules/Service/AppointmentService.cs
> +
**Magic number 2.00**. Change that!

2020-12-13 15:34 UTC, danica1998 commented on Backend/Schedules/Service/AppointmentService.cs
> +            if (appointment == null) {
you can join those two if statements into one

2020-12-13 15:43 UTC, danica1998 approved these changes

2020-12-13 16:04 UTC, closed without merging