Feature web appointment recommendation
PSW-2020-ORG1/MedbayTech pull request #56
Opened 2020-12-12 18:19 UTC by VujicGit

2020-12-12 19:02 UTC, st3fan7 approved these changes

2020-12-12 19:21 UTC, jelena-vlajkov submitted a review, later dismissed
Great algorithm! 
Just delete the all commented lines and implement the method that's not implemented.

2020-12-12 19:21 UTC, jelena-vlajkov commented on Backend/Schedules/Service/AvailableAppointmentService.cs
>  }
If the entire class is commented, please delete it.

2020-12-12 19:21 UTC, jelena-vlajkov commented on Backend/Schedules/Service/StrategyPattern/DatePriorityStrategy.cs
> +        public DatePriorityStrategy(IAppointmentService appointmentService, IDoctorService doctorService)
Find a way to make number more configurable.

2020-12-12 19:21 UTC, jelena-vlajkov commented on Backend/Users/Model/Specialization.cs
>          public void SetId(int id)
Delete commented lines.

2020-12-12 19:21 UTC, jelena-vlajkov commented on Backend/Users/Model/Doctor.cs
>          }
Delete commented lines.

2020-12-12 19:21 UTC, jelena-vlajkov commented on Backend/Users/Repository/FileRepository/UserRepository.cs
>      }
Never leave a method unimplemented.

2020-12-12 19:21 UTC, jelena-vlajkov commented on Backend/Users/Repository/MySqlRepository/DoctorSqlRepository.cs
>      }
Delete commented lines.

2020-12-12 19:21 UTC, jelena-vlajkov commented on UnitTests/Examinations/ReportTests.cs
Delete commented lines.

2020-12-12 20:43 UTC, st3fan7 requested changes
Resolve conflict.

2020-12-13 13:53 UTC, OakenKnight approved these changes

2020-12-13 13:59 UTC, st3fan7 approved these changes

2020-12-13 14:00 UTC, merged