New feature ge appointment search by doctor and interval
PSW-2020-ORG1/MedbayTech pull request #64
Opened 2020-12-13 20:46 UTC by antonic901

2020-12-15 17:33 UTC, OakenKnight commented on Backend/Rooms/Repository/FileRepository/EquipmentTypeRepository.cs
> +            throw new NotImplementedException();
implement all not implemented method

2020-12-15 17:33 UTC, OakenKnight commented on Backend/Rooms/Repository/FileRepository/EquipmentTypeRepository.cs
> +            throw new NotImplementedException();
even better delete all file repositories that are causing problems and resolve conflicts

2020-12-15 18:27 UTC, OakenKnight commented on Backend/Users/Service/PatientService.cs
>          private IAppointmentRepository appointmentRepository;
instead of appointmentRepository, should be _appointmentRepository

2020-12-15 18:32 UTC, OakenKnight commented on GraphicEditorWebService/Controllers/AppointmentFilterController.cs
> +                return Ok(_appointmentFilterService.GetAvailableByDoctorTimeIntervalAndEquipment(new PriorityParameters { DoctorId = appointmentFilterDTO.DoctorId, ChosenStartDate = appointmentFilter
instead of using numbers use some kind of Enum

2020-12-15 18:35 UTC, OakenKnight commented on Backend/Rooms/Service/EquipmentTypeService.cs
>          public EquipmentTypeRepository equipmentTypeRepository;
remove unnecessary instance of EquipmentTypeRepository

2020-12-15 18:37 UTC, OakenKnight commented on Backend/Rooms/Repository/MySqlRepository/EquipmentTypeSqlRepository.cs
>      {
should inherit MySqlRepository and IEquipmentTypeRepository

2020-12-15 18:38 UTC, jelena-vlajkov requested changes
Please change all suggestions. If you think something should stay the same, please let me know.

2020-12-15 18:38 UTC, jelena-vlajkov commented on GraphicEditorWebService/Controllers/AppointmentFilterController.cs
> +        }
Please make operations more clear. You can use enums.

2020-12-15 18:38 UTC, jelena-vlajkov commented on GraphicEditorWebService/Controllers/EquipmentTypeController.cs
> +    }
Same here, I don't know what 0 operation is.

2020-12-15 18:38 UTC, jelena-vlajkov commented on GraphicEditorWebService/Controllers/HospitalEquipmentController.cs
>      }
Same here.

2020-12-15 18:38 UTC, jelena-vlajkov commented on GraphicEditorWebService/Controllers/MedicalRecordController.cs
> +}
Same here.

2020-12-15 18:38 UTC, jelena-vlajkov commented on GraphicEditorWebService/Controllers/PatientController.cs
> +}
Same here.

2020-12-15 18:38 UTC, jelena-vlajkov commented on Backend/Rooms/Service/EquipmentTypeService.cs
> +        public IEquipmentTypeRepository _equipmentTypeRepository;
Delete line 13.

2020-12-15 18:38 UTC, jelena-vlajkov commented on Backend/Rooms/Repository/MySqlRepository/EquipmentTypeSqlRepository.cs
>      {
You should make EquipmentTypeSqlRepository inherit MySqlRepository.

2020-12-15 18:38 UTC, jelena-vlajkov commented on Backend/Rooms/Repository/MySqlRepository/EquipmentTypeSqlRepository.cs
> +        }
When you inherit MySqlRepository you can delete methods like Update, Delete, Create, GetObject.

2020-12-15 18:39 UTC, OakenKnight requested changes, later dismissed
Correct changes

2020-12-19 20:22 UTC, jelena-vlajkov approved these changes

2020-12-19 20:23 UTC, st3fan7 approved these changes

2020-12-19 20:25 UTC, merged