:bug: Fixed problems with vue client in PharmacyIntegration
PSW-2020-ORG1/MedbayTech pull request #78
Opened 2020-12-20 19:40 UTC by jelena-vlajkov

2020-12-20 19:46 UTC, danica1998 approved these changes

2020-12-20 20:24 UTC, OakenKnight approved these changes

2020-12-20 20:29 UTC, OakenKnight requested changes
Change !env.IsDevelopment()

2020-12-20 22:23 UTC, st3fan7 approved these changes

2020-12-21 00:26 UTC, OakenKnight approved these changes

2020-12-21 00:26 UTC, merged