:bug: Fixed bug with getting malicious patients
PSW-2020-ORG1/MedbayTech pull request #82
Opened 2020-12-23 22:05 UTC by ognjen98

2020-12-23 23:29 UTC, jelena-vlajkov requested changes

2020-12-23 23:29 UTC, jelena-vlajkov commented on Backend/Users/Service/PatientService.cs
> +        }
Is line 55 necessary because it is already set to true?

2020-12-24 15:09 UTC, jelena-vlajkov approved these changes

2020-12-24 20:17 UTC, st3fan7 approved these changes
👌

2020-12-24 20:18 UTC, merged